//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef CVPCS_ESP32_NATIVE_H
#define CVPCS_ESP32_NATIVE_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_cvpcs_Esp32_Native_cvpcs_Esp32_Native_AdcChannelExtensions
{
    NANOCLR_NATIVE_DECLARE(NativeCalRawToVoltage___STATIC__I4__I4__I4);

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_cvpcs_Esp32_Native;

#endif // CVPCS_ESP32_NATIVE_H
