//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "cvpcs_Esp32_Native.h"
#include "cvpcs_Esp32_Native_cvpcs_Esp32_Native_AdcChannelExtensions.h"

using namespace cvpcs_Esp32_Native::cvpcs_Esp32_Native;

HRESULT Library_cvpcs_Esp32_Native_cvpcs_Esp32_Native_AdcChannelExtensions::NativeCalRawToVoltage___STATIC__I4__I4__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        signed int channelNumber;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, channelNumber ) );

        signed int raw;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 1, raw ) );

        signed int retValue = AdcChannelExtensions::NativeCalRawToVoltage( channelNumber, raw, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}
