//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "cvpcs_Esp32_Native.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_cvpcs_Esp32_Native_cvpcs_Esp32_Native_AdcChannelExtensions::NativeCalRawToVoltage___STATIC__I4__I4__I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_cvpcs_Esp32_Native =
{
    "cvpcs.Esp32.Native",
    0xB21C34F1,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
